sudo: required
services:
  - docker

before_install:
  - docker pull mantlpkg/multitool

script:
  - docker run --rm -v $(pwd):/src mantlpkg/multitool build
  - docker run --rm -v $(pwd):/src mantlpkg/multitool test install
